{
    "name": "bank",
    'depends':['base','mail'],
    "data": [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',

        "wizard/finance_on_states_wizard.xml",
        "wizard/finance_on_localities_wizard.xml",
        # "wizard/finance_on_section_wizard.xml",
        # "wizard/finance_on_finance_type_wizard.xml",
        # "wizard/finance_on_formula_wizard.xml",
        "wizard/operations_maid_wizard.xml",
        # "wizard/finance_on_activity_wizard.xml",
        # "wizard/operations_maid_on_finance_type_wizard.xml",
        # "wizard/operations_maid_on_section_wizard.xml",
        # "wizard/operations_maid_on_activity_wizard.xml",
        # "wizard/operations_maid_on_formula_wizard.xml",
        "wizard/operations_rescheduling_wizard.xml",
        # "wizard/operations_rescheduling_on_finance_type_wizard.xml",
        # "wizard/operations_rescheduling_on_section_wizard.xml",
        # "wizard/operations_rescheduling_on_section_wizard.xml",
        # "wizard/operations_rescheduling_on_activity_wizard.xml",
        # "wizard/operations_rescheduling_on_formula_wizard.xml",
        "wizard/operations_stumbleds_wizard.xml",
        # "wizard/operations_stumbleds_on_finance_type_wizard.xml",
        # "wizard/operations_stumbleds_on_section_wizard.xml",
        # "wizard/operations_stumbleds_on_activity_wizard.xml",
        # "wizard/operations_stumbleds_on_formula_wizard.xml",
        "wizard/operations_trans_to_management_law_wizadrd.xml",
        # "wizard/operations_stansferred_to_the_courts_wizard.xml",


        "wizard/finances_requestes_wizard.xml",
        # "wizard/finances_requestes_section_wizard.xml",
        # "wizard/finances_requestes_activity_wizard.xml",
        # "wizard/finances_requestes_formula_wizard.xml",
        # "wizard/finances_requestes_finType_wizard.xml",
        # "wizard/approved_requestes_finType_wizard.xml",
        # "wizard/rejection_requestes_finType_wizard.xml",
        "wizard/approved_requestes_wizard.xml",
        # "wizard/approved_requestes_section_wizard.xml",
        # "wizard/approved_requestes_activity_wizard.xml",
        # "wizard/approved_requestes_formula_wizard.xml",
        "wizard/rejection_requestes_wizard.xml",
        # "wizard/rejection_requestes_section_wizard.xml",
        # "wizard/rejection_requestes_activity_wizard.xml",
        # "wizard/rejection_requestes_formula_wizard.xml",
        "wizard/first_payments_customer_wizard.xml",
        "wizard/transaction_installments_wizard.xml",
        "wizard/installment_payments_wizard.xml",
        "wizard/installment_not_payments_wizard.xml",
        "wizard/filtered_transaction_wizard.xml",
        # "wizard/filtered_transaction_section_wizard.xml",
        # "wizard/filtered_transaction_activity_wizard.xml",
        # "wizard/filtered_transaction_formula_wizard.xml",
        # "wizard/filtered_transaction_finType_wizard.xml",




        "views/views.xml",

        "report/finance_on_states_template.xml",
        "report/finance_on_localities_template.xml",
        # "report/finance_on_section_template.xml",
        # "report/finance_on_formula_template.xml",
        # "report/finance_on_activity_template.xml",
        # "report/finance_on_finance_type_template.xml",
        "report/operations_maid_template.xml",
        # "report/operations_maid_on_finance_type_temlate.xml",
        # "report/operations_maid_on_section_template.xml",
        # "report/operations_maid_on_activity_temlate.xml",
        # "report/operations_maid_on_formula_template.xml",
        "report/operations_rescheduling_template.xml",
        "report/operations_stumbleds_template.xml",
        # "report/operations_stumbleds_on_finance_type_template.xml",
        # "report/operations_stumbleds_on_section_template.xml",
        "report/operations_trans_to_management_law_template.xml",



        "report/finances_requestes_template.xml",
        # "report/finances_requestes_section_template.xml",
        # "report/finances_requestes_activity_template.xml",
        # "report/finances_requestes_formula_template.xml",
        # "report/finances_requestes_finType_template.xml",
        # "report/approved_requestes_finType_template.xml",
        # "report/rejection_requestes_finType_template.xml",
        "report/approved_requestes_template.xml",
        # "report/approved_requestes_section_template.xml",
        # "report/approved_requestes_activity_template.xml",
        # "report/approved_requestes_formula_template.xml",
        "report/rejection_requestes_template.xml",
        # "report/rejection_requestes_section_template.xml",
        # "report/rejection_requestes_activity_template.xml",
        # "report/rejection_requestes_formula_template.xml",
        "report/first_payments_customers_template.xml",
        "report/transaction_installments_template.xml",
        "report/installment_payments_template.xml",
        "report/filtered_transaction_template.xml",
        # "report/filtered_transaction_finType_template.xml",
        # "report/filtered_transaction_activity_template.xml",
        # "report/filtered_transaction_formula_template.xml",


    ]

}
